application: appomodoro
version: 2
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /czz/.*
  script: czz.py

- url: /default\.appcache
  mime_type: text/cache-manifest
  static_files: default.appcache
  upload: default\.appcache
  
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico
  
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /sounds
  static_dir: sounds
  
- url: /flash
  static_dir: flash
  
- url: /xmpp.*
  script: xmpp.py
  login: required
  
- url: /pomodoro
  script: pomodoro.py

- url: /descanso
  script: pomodoro.py
  
- url: /_ah/xmpp/message/chat/
  script: incomingXMPP.py
  
- url: /sendmail
  script: sendMail.py
  
- url: /.*
  script: main.py
